package PaginaPrincipal;

import AccionEspecial.AccionBotones;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class PaginaPrincipal extends javax.swing.JFrame {
    
    AccionBotones accionBotones = new AccionBotones();
    
    public PaginaPrincipal() {
        
        initComponents();
        
        this.setTitle("Pagina Principal");
        this.setExtendedState(6);
        this.getContentPane().setBackground(Color.white);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaInicio = new javax.swing.JPanel();
        bsalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PanelCambio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cambiarPanelMenu = new javax.swing.JPanel();
        bMatricular = new rojeru_san.rsbutton.RSButtonEffect();
        bAlumnos = new rojeru_san.rsbutton.RSButtonEffect();
        bCatequistas = new rojeru_san.rsbutton.RSButtonEffect();
        bParroc = new rojeru_san.rsbutton.RSButtonEffect();
        bPaseAno = new rojeru_san.rsbutton.RSButtonEffect();
        bReporte = new rojeru_san.rsbutton.RSButtonEffect();
        bFeBautismo = new rojeru_san.rsbutton.RSButtonEffect();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cajaInicio.setBackground(new java.awt.Color(221, 87, 76));

        bsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salida.png"))); // NOI18N
        bsalir.setContentAreaFilled(false);
        bsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Parroquia \"SAN PEDRO\"");

        javax.swing.GroupLayout cajaInicioLayout = new javax.swing.GroupLayout(cajaInicio);
        cajaInicio.setLayout(cajaInicioLayout);
        cajaInicioLayout.setHorizontalGroup(
            cajaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaInicioLayout.createSequentialGroup()
                .addContainerGap(522, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(378, 378, 378)
                .addComponent(bsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cajaInicioLayout.setVerticalGroup(
            cajaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bsalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cajaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(cajaInicio);
        cajaInicio.setBounds(0, 0, 1370, 63);

        PanelCambio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("SISTEMA PARROQUIA SAN PEDRO");

        javax.swing.GroupLayout PanelCambioLayout = new javax.swing.GroupLayout(PanelCambio);
        PanelCambio.setLayout(PanelCambioLayout);
        PanelCambioLayout.setHorizontalGroup(
            PanelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCambioLayout.createSequentialGroup()
                .addGroup(PanelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCambioLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(PanelCambioLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        PanelCambioLayout.setVerticalGroup(
            PanelCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCambioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(118, 118, 118)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        getContentPane().add(PanelCambio);
        PanelCambio.setBounds(320, 70, 1173, 635);

        cambiarPanelMenu.setBackground(new java.awt.Color(204, 204, 204));

        bMatricular.setBackground(new java.awt.Color(187, 186, 186));
        bMatricular.setForeground(new java.awt.Color(51, 51, 51));
        bMatricular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoMatricula.png"))); // NOI18N
        bMatricular.setText("      Inicio/Matricular");
        bMatricular.setAlignmentY(0.0F);
        bMatricular.setColorHover(new java.awt.Color(171, 170, 170));
        bMatricular.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMatricularActionPerformed(evt);
            }
        });

        bAlumnos.setBackground(new java.awt.Color(187, 186, 186));
        bAlumnos.setForeground(new java.awt.Color(51, 51, 51));
        bAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoAlumno.png"))); // NOI18N
        bAlumnos.setText("      Alumnos");
        bAlumnos.setAlignmentY(0.0F);
        bAlumnos.setColorHover(new java.awt.Color(171, 170, 170));
        bAlumnos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlumnosActionPerformed(evt);
            }
        });

        bCatequistas.setBackground(new java.awt.Color(187, 186, 186));
        bCatequistas.setForeground(new java.awt.Color(51, 51, 51));
        bCatequistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconocatequista.png"))); // NOI18N
        bCatequistas.setText("      Catequistas");
        bCatequistas.setAlignmentY(0.0F);
        bCatequistas.setColorHover(new java.awt.Color(171, 170, 170));
        bCatequistas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bCatequistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCatequistasActionPerformed(evt);
            }
        });

        bParroc.setBackground(new java.awt.Color(187, 186, 186));
        bParroc.setForeground(new java.awt.Color(51, 51, 51));
        bParroc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoSacerdote.png"))); // NOI18N
        bParroc.setText("      Párroco");
        bParroc.setAlignmentY(0.0F);
        bParroc.setColorHover(new java.awt.Color(171, 170, 170));
        bParroc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bParroc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParrocActionPerformed(evt);
            }
        });

        bPaseAno.setBackground(new java.awt.Color(187, 186, 186));
        bPaseAno.setForeground(new java.awt.Color(51, 51, 51));
        bPaseAno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoPase.png"))); // NOI18N
        bPaseAno.setText("      Pase de Año");
        bPaseAno.setAlignmentY(0.0F);
        bPaseAno.setColorHover(new java.awt.Color(171, 170, 170));
        bPaseAno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bPaseAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPaseAnoActionPerformed(evt);
            }
        });

        bReporte.setBackground(new java.awt.Color(187, 186, 186));
        bReporte.setForeground(new java.awt.Color(51, 51, 51));
        bReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoReporte.png"))); // NOI18N
        bReporte.setText("      Reporte");
        bReporte.setAlignmentY(0.0F);
        bReporte.setColorHover(new java.awt.Color(171, 170, 170));
        bReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReporteActionPerformed(evt);
            }
        });

        bFeBautismo.setBackground(new java.awt.Color(187, 186, 186));
        bFeBautismo.setForeground(new java.awt.Color(51, 51, 51));
        bFeBautismo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconobautizo.png"))); // NOI18N
        bFeBautismo.setText("      Fe de Bautismo");
        bFeBautismo.setAlignmentY(0.0F);
        bFeBautismo.setColorHover(new java.awt.Color(171, 170, 170));
        bFeBautismo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bFeBautismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFeBautismoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cambiarPanelMenuLayout = new javax.swing.GroupLayout(cambiarPanelMenu);
        cambiarPanelMenu.setLayout(cambiarPanelMenuLayout);
        cambiarPanelMenuLayout.setHorizontalGroup(
            cambiarPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cambiarPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cambiarPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bMatricular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(bCatequistas, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(bParroc, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(bPaseAno, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(bReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(bFeBautismo, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addContainerGap())
        );
        cambiarPanelMenuLayout.setVerticalGroup(
            cambiarPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cambiarPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCatequistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bParroc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bPaseAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(bFeBautismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        getContentPane().add(cambiarPanelMenu);
        cambiarPanelMenu.setBounds(10, 70, 290, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bsalirActionPerformed
    

    private void bMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMatricularActionPerformed
        accionBotones.botonMatricula(PanelCambio);
    }//GEN-LAST:event_bMatricularActionPerformed

    private void bAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlumnosActionPerformed
        accionBotones.botonAlumnos(PanelCambio);
    }//GEN-LAST:event_bAlumnosActionPerformed

    private void bCatequistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCatequistasActionPerformed
        accionBotones.botonCatequista(PanelCambio);
    }//GEN-LAST:event_bCatequistasActionPerformed

    private void bParrocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParrocActionPerformed
        accionBotones.botonParroco(PanelCambio);
    }//GEN-LAST:event_bParrocActionPerformed

    private void bPaseAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPaseAnoActionPerformed
        accionBotones.botonPaseAno(PanelCambio);
    }//GEN-LAST:event_bPaseAnoActionPerformed

    private void bReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReporteActionPerformed
        accionBotones.botonReporte(PanelCambio);
    }//GEN-LAST:event_bReporteActionPerformed

    private void bFeBautismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFeBautismoActionPerformed
        try {
            accionBotones.botonFeBautismo(PanelCambio);
        } catch (SQLException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bFeBautismoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelCambio;
    private rojeru_san.rsbutton.RSButtonEffect bAlumnos;
    private rojeru_san.rsbutton.RSButtonEffect bCatequistas;
    private rojeru_san.rsbutton.RSButtonEffect bFeBautismo;
    private rojeru_san.rsbutton.RSButtonEffect bMatricular;
    private rojeru_san.rsbutton.RSButtonEffect bParroc;
    private rojeru_san.rsbutton.RSButtonEffect bPaseAno;
    private rojeru_san.rsbutton.RSButtonEffect bReporte;
    private javax.swing.JButton bsalir;
    private javax.swing.JPanel cajaInicio;
    private javax.swing.JPanel cambiarPanelMenu;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
